<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ImplicitUsings>disable</ImplicitUsings>
    <Authors>Garage contributors</Authors>
  </PropertyGroup>
</Project>
