using UnityEditor;
using UnityEngine;

namespace Garage.Unity.EditorTools
{
    /// <summary>
    /// Import rules for the models generated by tools/blender/models.py (Assets/Garage/Resources/**.fbx):
    /// real scale (1 unit = 1 m, file units), no animation, materials from the FBX material description (HDRP/Lit),
    /// LODGroup from the *_LOD0/1/2 naming, and UCX_* boxes turned into convex MeshColliders without a renderer.
    /// </summary>
    public sealed class GarageModelPostprocessor : AssetPostprocessor
    {
        private bool IsGarageModel => assetPath.Replace('\\', '/').Contains("Assets/Garage/Resources/") && assetPath.ToLowerInvariant().EndsWith(".fbx");

        private void OnPreprocessModel()
        {
            if (!IsGarageModel)
            {
                return;
            }

            var importer = (ModelImporter)assetImporter;
            importer.globalScale = 1f;
            importer.useFileScale = true;
            importer.importAnimation = false;
            importer.importCameras = false;
            importer.importLights = false;
            importer.addCollider = false;
            importer.materialImportMode = ModelImporterMaterialImportMode.ImportViaMaterialDescription;
        }

        private void OnPostprocessModel(GameObject root)
        {
            if (!IsGarageModel)
            {
                return;
            }

            foreach (MeshFilter mf in root.GetComponentsInChildren<MeshFilter>(true))
            {
                if (!mf.name.StartsWith("UCX_"))
                {
                    continue;
                }

                MeshCollider mc = mf.gameObject.AddComponent<MeshCollider>();
                mc.sharedMesh = mf.sharedMesh;
                mc.convex = true;
                MeshRenderer r = mf.GetComponent<MeshRenderer>();
                if (r != null)
                {
                    Object.DestroyImmediate(r);
                }
            }
        }
    }
}
