<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>Garage.Data</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Garage.Sim\Garage.Sim.csproj" />
  </ItemGroup>
</Project>
